/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabelsRouteImport } from './routes/labels'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DbServersIndexRouteImport } from './routes/db-servers.index'
import { Route as DatabasesIndexRouteImport } from './routes/databases.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DatabasesIdRouteImport } from './routes/databases.$id'
import { Route as DbServersIdIndexRouteImport } from './routes/db-servers.$id.index'
import { Route as DbServersIdDatabasesDbnameIndexRouteImport } from './routes/db-servers.$id.databases.$dbname.index'
import { Route as DbServersIdDatabasesDbnameErdRouteImport } from './routes/db-servers.$id.databases.$dbname.erd'
import { Route as DbServersIdDatabasesDbnameTablesSchemaTableRouteImport } from './routes/db-servers.$id.databases.$dbname.tables.$schema.$table'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsRoute = LabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbServersIndexRoute = DbServersIndexRouteImport.update({
  id: '/db-servers/',
  path: '/db-servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DatabasesIdRoute = DatabasesIdRouteImport.update({
  id: '/databases/$id',
  path: '/databases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DbServersIdIndexRoute = DbServersIdIndexRouteImport.update({
  id: '/db-servers/$id/',
  path: '/db-servers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DbServersIdDatabasesDbnameIndexRoute =
  DbServersIdDatabasesDbnameIndexRouteImport.update({
    id: '/db-servers/$id/databases/$dbname/',
    path: '/db-servers/$id/databases/$dbname/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DbServersIdDatabasesDbnameErdRoute =
  DbServersIdDatabasesDbnameErdRouteImport.update({
    id: '/db-servers/$id/databases/$dbname/erd',
    path: '/db-servers/$id/databases/$dbname/erd',
    getParentRoute: () => rootRouteImport,
  } as any)
const DbServersIdDatabasesDbnameTablesSchemaTableRoute =
  DbServersIdDatabasesDbnameTablesSchemaTableRouteImport.update({
    id: '/db-servers/$id/databases/$dbname/tables/$schema/$table',
    path: '/db-servers/$id/databases/$dbname/tables/$schema/$table',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/backups': typeof BackupsRoute
  '/labels': typeof LabelsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/databases/$id': typeof DatabasesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/databases': typeof DatabasesIndexRoute
  '/db-servers': typeof DbServersIndexRoute
  '/db-servers/$id': typeof DbServersIdIndexRoute
  '/db-servers/$id/databases/$dbname/erd': typeof DbServersIdDatabasesDbnameErdRoute
  '/db-servers/$id/databases/$dbname': typeof DbServersIdDatabasesDbnameIndexRoute
  '/db-servers/$id/databases/$dbname/tables/$schema/$table': typeof DbServersIdDatabasesDbnameTablesSchemaTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/backups': typeof BackupsRoute
  '/labels': typeof LabelsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/databases/$id': typeof DatabasesIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/databases': typeof DatabasesIndexRoute
  '/db-servers': typeof DbServersIndexRoute
  '/db-servers/$id': typeof DbServersIdIndexRoute
  '/db-servers/$id/databases/$dbname/erd': typeof DbServersIdDatabasesDbnameErdRoute
  '/db-servers/$id/databases/$dbname': typeof DbServersIdDatabasesDbnameIndexRoute
  '/db-servers/$id/databases/$dbname/tables/$schema/$table': typeof DbServersIdDatabasesDbnameTablesSchemaTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/backups': typeof BackupsRoute
  '/labels': typeof LabelsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/databases/$id': typeof DatabasesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/databases/': typeof DatabasesIndexRoute
  '/db-servers/': typeof DbServersIndexRoute
  '/db-servers/$id/': typeof DbServersIdIndexRoute
  '/db-servers/$id/databases/$dbname/erd': typeof DbServersIdDatabasesDbnameErdRoute
  '/db-servers/$id/databases/$dbname/': typeof DbServersIdDatabasesDbnameIndexRoute
  '/db-servers/$id/databases/$dbname/tables/$schema/$table': typeof DbServersIdDatabasesDbnameTablesSchemaTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/activity'
    | '/backups'
    | '/labels'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/storage'
    | '/databases/$id'
    | '/dashboard/'
    | '/databases'
    | '/db-servers'
    | '/db-servers/$id'
    | '/db-servers/$id/databases/$dbname/erd'
    | '/db-servers/$id/databases/$dbname'
    | '/db-servers/$id/databases/$dbname/tables/$schema/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/backups'
    | '/labels'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/storage'
    | '/databases/$id'
    | '/dashboard'
    | '/databases'
    | '/db-servers'
    | '/db-servers/$id'
    | '/db-servers/$id/databases/$dbname/erd'
    | '/db-servers/$id/databases/$dbname'
    | '/db-servers/$id/databases/$dbname/tables/$schema/$table'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/activity'
    | '/backups'
    | '/labels'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/storage'
    | '/databases/$id'
    | '/dashboard/'
    | '/databases/'
    | '/db-servers/'
    | '/db-servers/$id/'
    | '/db-servers/$id/databases/$dbname/erd'
    | '/db-servers/$id/databases/$dbname/'
    | '/db-servers/$id/databases/$dbname/tables/$schema/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  BackupsRoute: typeof BackupsRoute
  LabelsRoute: typeof LabelsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  DatabasesIdRoute: typeof DatabasesIdRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
  DbServersIndexRoute: typeof DbServersIndexRoute
  DbServersIdIndexRoute: typeof DbServersIdIndexRoute
  DbServersIdDatabasesDbnameErdRoute: typeof DbServersIdDatabasesDbnameErdRoute
  DbServersIdDatabasesDbnameIndexRoute: typeof DbServersIdDatabasesDbnameIndexRoute
  DbServersIdDatabasesDbnameTablesSchemaTableRoute: typeof DbServersIdDatabasesDbnameTablesSchemaTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels': {
      id: '/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-servers/': {
      id: '/db-servers/'
      path: '/db-servers'
      fullPath: '/db-servers'
      preLoaderRoute: typeof DbServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/databases/$id': {
      id: '/databases/$id'
      path: '/databases/$id'
      fullPath: '/databases/$id'
      preLoaderRoute: typeof DatabasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-servers/$id/': {
      id: '/db-servers/$id/'
      path: '/db-servers/$id'
      fullPath: '/db-servers/$id'
      preLoaderRoute: typeof DbServersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-servers/$id/databases/$dbname/': {
      id: '/db-servers/$id/databases/$dbname/'
      path: '/db-servers/$id/databases/$dbname'
      fullPath: '/db-servers/$id/databases/$dbname'
      preLoaderRoute: typeof DbServersIdDatabasesDbnameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-servers/$id/databases/$dbname/erd': {
      id: '/db-servers/$id/databases/$dbname/erd'
      path: '/db-servers/$id/databases/$dbname/erd'
      fullPath: '/db-servers/$id/databases/$dbname/erd'
      preLoaderRoute: typeof DbServersIdDatabasesDbnameErdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-servers/$id/databases/$dbname/tables/$schema/$table': {
      id: '/db-servers/$id/databases/$dbname/tables/$schema/$table'
      path: '/db-servers/$id/databases/$dbname/tables/$schema/$table'
      fullPath: '/db-servers/$id/databases/$dbname/tables/$schema/$table'
      preLoaderRoute: typeof DbServersIdDatabasesDbnameTablesSchemaTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  BackupsRoute: BackupsRoute,
  LabelsRoute: LabelsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  DatabasesIdRoute: DatabasesIdRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
  DbServersIndexRoute: DbServersIndexRoute,
  DbServersIdIndexRoute: DbServersIdIndexRoute,
  DbServersIdDatabasesDbnameErdRoute: DbServersIdDatabasesDbnameErdRoute,
  DbServersIdDatabasesDbnameIndexRoute: DbServersIdDatabasesDbnameIndexRoute,
  DbServersIdDatabasesDbnameTablesSchemaTableRoute:
    DbServersIdDatabasesDbnameTablesSchemaTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
